### ISSUE TITLE
The Moonson profiler is too unstable

### ISSUE THREAD

**Issue by sshann** [S2-group/android-runner#37]
These are issues I encountered when trying to set up the experiment using the Moonson profiler.
Due to time constraints, I switched profilers but kept notes on what we were unable to resolve.

These were encountered with the mobile device provided by Ivano, a Nexus 5X, modified in the hardware-level to enable its usage with Moonson.

### Turning the display on and off in incorrect occasions and freezing the computation while the display was off.
 
The Moonson profiler turns the display on when starting the profiling and off and finalizing the profiling (see code below).
I had the following behaviours when running the experiment with the profiler:

1. The mobile device display was not turning on when AR started the profiling process
1. The execution would freeze after the profiling finish and the mobile device display was turned off. The execution would only resume after manually turning on the mobile device display. Trying to turn it on programmatically via ADB outside AR did not resolve.

The first behaviour was rare, however, the second behaviour occurred frequently.
After discussing with Eric, he explained that this is only required to avoid the mobile device screen sleeping while running the experiment. 
Although the mobile device has an option to disable sleeping while charging, the Moonsoon profiler manages the charging state.
This means that the mobile device would not be always charging.
Since my experiment was based on interactions, the mobile device would never hit the idle timer to sleep, so I removed the lines for these commands.

https://github.com/S2-group/android-runner/blob/35ae4f6a313313e980608e75425639b9edeccae7/AndroidRunner/Plugins/monsoon/Monsoon.py#L25-L36

### Mobile device randomly turning off or rebooting

The mobile device turns off or rebooting while running the experiment.
Initially, this was a random event, occurring 2 to 3 times a day.
At some point, this started occurring in every experiment.
This issue might be at the hardware level rather than the profiler level.
No solution or alternative was found to this issue, thus motivating switching to another profiler.

**Comment by EricZielinski** [comment]
I experienced an issue about once every 24 hours in my own experiments.  The applications I tested were ones which didn't require any user interaction.  According to Monsoon, their customers run experiments that last for several days or beyond a week, so there's definitely room to make this plugin more robust.  Here are my suggestions:

- For one, I ran my experiments at 3.8 volts; Monsoon normally uses 4 to 4.2 volts during their own testing process, so that be one thing to look into that might help the device from turning itself off.  
- Test another Nexus 5X and/or another model.  Obviously, this comes at a cost, so see if the above improves anything first if a new device needs to be configured.  The issues may stem from preparing the device to use the power monitor: removing the battery and re-establishing the circuit manually

**Comment by odmnk** [comment]
After testing the freezes occurred when sending a command to the device through ADB. This could take up to 8 minutes and there are multiple of these commands in a single run.  

This was probably caused because of the combination of ADB through WiFi, the phone that is in sleep mode and that the device is not connected through USB at all. See for more info this PR that fixes this: https://github.com/S2-group/android-runner/pull/70

I've done multiple test experiments (some upto 27+ hours) and the problem did not occur. So it seems to be fixed.

Regarding the problem of devices randomly turning off; I didn't experience that problem even after extensive testing. IIRC we used a different Nexus 5X so that may explain it.
