### ISSUE TITLE
issue in batterystats

### ISSUE THREAD

**Issue by umkhanqta** [S2-group/android-runner#53]
Hi,
   I try to run batterystats plugin, set all the path correctly
but I am getting error
`File "android-runner/AndroidRunner/Plugins/batterystats/BatterystatsParser.py", line 447, in parse_logcat
    app_start_date = re.findall(app_start_pattern, logcat)[0][0]
IndexError: list index out of range

NativeExperiment: IndexError: list index out of range`
I searched the output of logcat_file but it did not contain line of ActivityManager: Displayed
Kindly help me out

**Comment by EricZielinski** [comment]
I ran into similar problems; you're the first person to also experience this issue.  For some reason, the shell command `logcat -f` doesn't work, as in, it doesn't create a file on the device.  My work around will require editing Batterystats.py in `AndroidRunner/Plugins/Batterystats`:
```
    @staticmethod
    def pull_logcat(device):
        with open(logcat_file, 'w+') as output:
            subprocess.Popen(["adb", "logcat", "-d"], stdout=output)
        time.sleep(2)
        # device.shell('logcat -f /mnt/sdcard/logcat.txt -d')
        # device.pull('/mnt/sdcard/logcat.txt', logcat_file)
        # device.shell('rm -f /mnt/sdcard/logcat.txt')
```
You'll also experience issues with the garbagecollection profiler because it uses the same shell command.  I will update the framework with this workaround for both profilers sometime this week as a backup to the commented out code above.

**Comment by EricZielinski** [comment]
Are you using an emulator?  If so, I don't have a regular expression for this particular problem like I did with https://github.com/S2-group/android-runner/issues/50.

**Comment by umkhanqta** [comment]
Yes, I am using an emulator.  I will try to get results from the physical devices. Thanks
